name: MC
title: MC | The elusive chanteuse
description: I don't know daaaahling, what do you think?
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
email: zhiyuanma0401@gmail.com
disqus_username: 
